// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyuh3KqmYim-ntESwOY088A5gbG4zW-1A',
    appId: '1:129684131304:web:39fa2efc95e0af2acd685d',
    messagingSenderId: '129684131304',
    projectId: 'vibe-connect-a4616',
    authDomain: 'vibe-connect-a4616.firebaseapp.com',
    storageBucket: 'vibe-connect-a4616.firebasestorage.app',
    measurementId: 'G-CWRJ5H4XSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpTSCCOvooV4MZkzke9rZ8g_q10eoJooU',
    appId: '1:129684131304:android:1dc46c6ce9b12442cd685d',
    messagingSenderId: '129684131304',
    projectId: 'vibe-connect-a4616',
    storageBucket: 'vibe-connect-a4616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA42lPVmZ8MFdpl1Gt8LVHNnUgh0scO9Q',
    appId: '1:129684131304:ios:0e1ad68682780aafcd685d',
    messagingSenderId: '129684131304',
    projectId: 'vibe-connect-a4616',
    storageBucket: 'vibe-connect-a4616.firebasestorage.app',
    androidClientId: '129684131304-mfqvnmebp7mb3f8ijpop2g4200rci5mk.apps.googleusercontent.com',
    iosClientId: '129684131304-hllqap2m1ivnivuqqogu8421pd04opfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA42lPVmZ8MFdpl1Gt8LVHNnUgh0scO9Q',
    appId: '1:129684131304:ios:0e1ad68682780aafcd685d',
    messagingSenderId: '129684131304',
    projectId: 'vibe-connect-a4616',
    storageBucket: 'vibe-connect-a4616.firebasestorage.app',
    androidClientId: '129684131304-mfqvnmebp7mb3f8ijpop2g4200rci5mk.apps.googleusercontent.com',
    iosClientId: '129684131304-hllqap2m1ivnivuqqogu8421pd04opfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyuh3KqmYim-ntESwOY088A5gbG4zW-1A',
    appId: '1:129684131304:web:a498782302567915cd685d',
    messagingSenderId: '129684131304',
    projectId: 'vibe-connect-a4616',
    authDomain: 'vibe-connect-a4616.firebaseapp.com',
    storageBucket: 'vibe-connect-a4616.firebasestorage.app',
    measurementId: 'G-6T61Q09Z0D',
  );
}
